use role sysadmin;

SELECT SYSTEM$CLUSTERING_INFORMATION(
    'SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM',
    '(l_orderkey)'
);

SELECT SYSTEM$CLUSTERING_INFORMATION(
    'SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM',
    '(l_partkey)'
);

SELECT SYSTEM$CLUSTERING_INFORMATION(
    'SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM',
    '(l_suppkey)'
);

SELECT SYSTEM$CLUSTERING_INFORMATION(
    'SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM',
    '(l_receiptdate)'
);